JuliaSmoothOptimizers/LinearOperators.jl

- .travis.yml
- REQUIRE
- appveyor.yml
- src/LinearOperators.jl
- src/lbfgs.jl
- src/lsr1.jl
- test/runtests.jl
- test/test_cat.jl
- test/test_linop.jl
Addresses #13.
This is quite a large change. The idea is to take advantage of Julia's parametric types instead of building the type directly in the operator.
I'll comment on a couple of sticky points in the code below.
@abelsiqueira
> Overhaul of operator types

- README.md
- src/LinearOperators.jl
- test/test_linop.jl
* rename RestrictionOperator -> opRestriction
* rename ExtensionOperator -> opExtension
* generalize both to slices and Colon operator
* update README
Closes #20.
> generalize opRestriction and opExtension

- .travis.yml
- appveyor.yml
- src/LinearOperators.jl
Some incompatibilities remain. I had to remove .+ and similar, so I changed it for + alone.
> Some changes to pass on Julia 0.6

- src/LinearOperators.jl
> Add @static version check for . operations

- test/test_lbfgs.jl
Fix https://travis-ci.org/JuliaSmoothOptimizers/LinearOperators.jl/jobs/274858987#L537
> Fix random error testing BFGS data.insert

- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- src/LinearOperators.jl
- src/kron.jl
- src/lbfgs.jl
- src/lsr1.jl
- test/runtests.jl
- test/test_cat.jl
- test/test_kron.jl
- test/test_lbfgs.jl
- test/test_linop.jl
- test/test_lsr1.jl
> [WIP] Updates to Julia 0.7 and drop 0.4 and 0.5

- docs/src/index.md
- docs/src/tutorial.md
> Documentation updates

- docs/make.jl
> Change 0.5 to 0.6 on docs/make.jl

- .travis.yml
- REQUIRE
- appveyor.yml
- src/LinearOperators.jl
- src/kron.jl
- src/lbfgs.jl
- src/lsr1.jl
- src/qn.jl
- test/runtests.jl
- test/test_cat.jl
- test/test_kron.jl
- test/test_lbfgs.jl
- test/test_linop.jl
- test/test_lsr1.jl
> Drop 0.6 and update to 1.0

- src/lbfgs.jl
- test/test_lbfgs.jl
> Fix damping in L-BFGS

- src/LinearOperators.jl
- test/test_linop.jl
Rebased #64 and implemented tests. Added disclaimer that type is not enforced.
> Specify type

- src/LinearOperators.jl
- test/test_linop.jl
> Fix @. in mul!

- src/LinearOperators.jl
- src/PreallocatedLinearOperators.jl
- test/test_linop.jl
> Create prealloacted operators

- .travis.yml
- docs/Project.toml
- docs/make.jl
- docs/src/index.md
- docs/src/reference.md
- docs/src/tutorial.md
- src/lbfgs.jl
- src/lsr1.jl
> Doc update

- LICENSE.md
- README.md
- Changes LICENSE to MPL2
- Adds Zenodo and `cite as`
> Update LICENSE and add Zenodo badge

- .travis.yml
- REQUIRE
- appveyor.yml
- test/runtests.jl
- test/test_aux.jl
- test/test_cat.jl
- test/test_kron.jl
- test/test_lbfgs.jl
- test/test_linop.jl
- test/test_lsr1.jl
Two small things:
- Changed `@assert` to `@test` in `test_lsr1.jl`;
- Dropped Julia 0.7 support;
Large changes:
- Created `simple_matrix` that generates a random matrix with singular values between 1 and 2;
- Created `simple_sparse_matrix` that generates a block diagonal matrix where each block is a `simple_matrix`;
- Created `simple_vector` for vector `[1; -1; 1; ...]`.
- Changed all `rand` to one of those three, or equivalent.
> Remove random

- src/LinearOperators.jl
- test/test_linop.jl
> fix posdef check for matrices + add tests

- src/LinearOperators.jl
- src/adjtrans.jl
- test/test_linop.jl
> Create adjoint, transpose and conjugate wrapper types

- src/adjtrans.jl
- test/test_linop.jl
> Implement unary - and scalar product for Adjoint and Transpose

- src/LinearOperators.jl
- test/test_linop.jl
> Fix bug with sum and cat between Adjoint/Transpose and other matrices

- src/PreallocatedLinearOperators.jl
- test/test_linop.jl
> Increase coverage of Preallocated Operators

- src/BlockDiagonalOperator.jl
- src/LinearOperators.jl
- test/test_linop.jl
> add block-diagonal linear operator

- Project.toml
> Version 1.0.0

- Project.toml
- docs/src/index.md
> Remove wrong license in docs and update to 1.0.1

- Project.toml
> Version 1.3.1

- .github/workflows/Breakage.yml
> Update workflow Breakage.yml

- src/TimedOperators.jl
- src/abstract.jl
- src/adjtrans.jl
- src/cat.jl
- src/constructors.jl
- src/lbfgs.jl
- src/lsr1.jl
- src/operations.jl
- src/special-operators.jl
- test/test_lbfgs.jl
- test/test_linop.jl
- test/test_lsr1.jl
@dpo @amontoison what do you think about this to define operators that only use the 3-args `mul!`? I can change the name of the constructor
Should I also add the `@closure` macro to the functions inside the new constructor?
> 3-args operators

- src/adjtrans.jl
- test/test_linop.jl
This PR should fix https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/issues/199 .
> Fix bug when tprod! is not provided

- .buildkite/pipeline.yml
- test/gpu/nvidia.jl
> Setup buildkite

- Project.toml
- ext/LinearOperatorsLDLFactorizationsExt.jl
- src/LinearOperators.jl
- src/linalg.jl
- test/runtests.jl
> Change LDLFactorizations to be a weakdep

- .github/workflows/Documentation.yml
see if julia 1.11 is the reason for push failures
> build docs with julia 1.10

- .github/workflows/CI.yml
> use LTS 1.10 in CI

- .buildkite/pipeline.yml
- .github/workflows/CI.yml
- src/abstract.jl
- src/deprecated.jl
- src/lbfgs.jl
- src/lsr1.jl
- src/special-operators.jl
I also updated the CI script.
Reference for the modification: https://github.com/exanauts/ExaModels.jl/pull/124
> Use Type instead of DataType

- Project.toml
> Bump to 2.10
