.travis.yml, appveyor.yml
This drops 0.6.
Maybe we could have 0.4.x for limited 0.6 support, and the next release (and current master) are 0.7 only.
Also closes #55.
=> Update to 0.7 - don't drop 0.6

src/LinearOperators.jl, test/test_linop.jl
`Krylov` breaks because of [this](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/symmlq.jl#L47).
=> Fix opEye bug

src/lbfgs.jl
J'ai modifié une ligne de la mise à jour du vecteur `a` dans la formule L-BFGS pour que le comportement soit le même que dans l'opérateur Spot en Matlab.
=> Corrected vector "a" update in lbfgs operator

README.md
The syntax for transpose in the main README was outdated. This updates it.
=> Update syntax for transpose in README

src/LinearOperators.jl, test/test_linop.jl
Following #66, perhaps we should consider a Bypass operator? This simply returns the Vector/Matrix/Operator. It doesn't handle any matrix information, but if you need a unsafe_opEye, then maybe Bypass could be used instead.
=> opEye operator

Project.toml, REQUIRE
Also, registering packages has changed to use [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl).
=> Change from REQUIRE to Project.toml

.travis.yml, appveyor.yml, src/LinearOperators.jl, test/test_cat.jl
hcat and vcat are still defined between one operator and one matrix.
Also updates travis and appveyor to run on Julia 1.3.
Closes #100
=> Removes {h,v,hv}cat between arbitrary number of operators and matrices

src/adjtrans.jl, test/runtests.jl, test/test_adjtrans.jl, test/test_linop.jl
=> Fix Conjugate Operator and test all adjoint/transpose/conjugate operations

src/LinearOperators.jl, src/PreallocatedLinearOperators.jl, src/adjtrans.jl, src/lbfgs.jl, src/lsr1.jl, test/test_linop.jl
=> add counters for products

src/kron.jl, test/test_kron.jl
=> convert types in kron multiply

docs/src/tutorial.md, src/LinearOperators.jl, src/adjtrans.jl, test/test_linop.jl
Necessary for https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/151
=> Annotate a few types to improve type inference and thus allocation

src/adjtrans.jl, src/operations.jl, test/test_linop.jl
=> Allows more generic matrix-vector products

src/lbfgs.jl, src/lsr1.jl, test/test_lbfgs.jl, test/test_lsr1.jl
The scaling factor wasn't reset to 1 when resetting the operator. This lead to non-reproducible results.
=> QN: reset scaling factor

src/lbfgs.jl, src/lsr1.jl, test/test_lbfgs.jl, test/test_lsr1.jl
I made `mem` a keyword arguments. The rest is all nitpicks.
=> minor updates to L-SR1 operator

docs/Project.toml, docs/src/assets/style.css
A small change to provide color to the sidebar. Here's how it looks like:
https://juliasmoothoptimizers.github.io/LinearOperators.jl/dev/
My proposal is to follow the same structure for all JSO packages (eventually).
=> Style proposal for JSO documentation

src/lbfgs.jl, test/test_lbfgs.jl
Basically:
```julia
B = LBFGSOperator(n, mem=mem)
H = InverseLBFGSOperator(n, mem=mem)
x = rand(n)
nallocs = @allocated B * x
@test nallocs == 0
nallocs = @allocated H * x
@test nallocs == 0
nallocs = @allocated diag!(B, x)
@test nallocs == 0
```
=> LBFGS: remove allocations

src/PreallocatedLinearOperators.jl
In Krylov.jl, we cannot use `Symmetric` matrices because `PreallocatedLinearOperator(M ::Symmetric{T}; storagetype, symmetric)` is not implemented.
This PR allows the use of symmetric and hermitian options even if they are not used with `Symmetric`, `Hermitian` and `SymTriadiagonal` wrappers.
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L24
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L62
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L65
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L73
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L76
=> Allows symmetric and hermitian options for all PreallocatedLinearOperator methods

.cirrus.yml, Project.toml, src/lbfgs.jl, src/lsr1.jl, test/runtests.jl, test/test_lbfgs.jl, test/test_lsr1.jl
=> define mul! for quasi-Newton operators

src/lbfgs.jl
Maybe slower for the damped case, but it was always allocating otherwise.
=> Remove unnecessary allocation in push!

src/lbfgs.jl, test/test_lbfgs.jl
Notice that `push(nlp, s, y)` allocates 80, possibly due to the default `g = eltype(y)[]`?
=> Improve LBFGS allocation

src/linalg.jl
In-place `conj` is `conj!`.
`conj` is equivalent to `conj.`, but the latter has the advantage of fusing with other dot calls.
=> Improve tmulFact! function

src/abstract.jl, test/test_linop.jl
`BlockDiagonalOperator(ops...)` is not working anymore if one operator is a matrix because `has_args5(op::AbstractMatrix)` is not defined. This pull request solves the problem.
=> Add has_args5 method for AbstractMatrix

src/abstract.jl
These functions should operate on `AbstractLinearOperator`. Otherwise one needs to define them for every new type again, which is also not necessary for the other (abstract) fields.
=> Make some functions work on AbstractLinearOperator

src/TimedOperators.jl, src/abstract.jl, src/adjtrans.jl, src/cat.jl, src/constructors.jl, src/lbfgs.jl, src/lsr1.jl, src/operations.jl, src/special-operators.jl
This is a PR to make LinearOperators such as  `op = op1 * op2`, `op = op1 + op2` ... and the 5-args `mul!` function from operators build upon the 3-args `mul!`  work on GPU.
The user has to specify the storage type in the constructor of all operators `op1` and `op2`:
```julia
op1 = LinearOperator(Float64, n, n, true, true, prod!, S = CuVector{Float64, 1, CUDA.Mem.DeviceBuffer})
```
Operators that are not "composite" (built with other operators) should already be working without this PR.
=> GPU compat with composite operators and 3-args mul!

src/utilities.jl
moving the     Sx = zeros(eltype(S), n) out of the loop
=> Reduce allocations in normest

src/abstract.jl
For externally defined operator types (i.e NFFTOp in MRIReco.jl) the following error is encountered: 
```
MethodError: no method matching storage_type(::NFFTOp{ComplexF64})
[371](https://github.com/MagneticResonanceImaging/MRIReco.jl/runs/6123878388?check_suite_focus=true#step:6:371)
Closest candidates are:
[372](https://github.com/MagneticResonanceImaging/MRIReco.jl/runs/6123878388?check_suite_focus=true#step:6:372)
storage_type(::LinearOperator) at /home/runner/.julia/packages/LinearOperators/ER4po/src/abstract.jl:168
[373](https://github.com/MagneticResonanceImaging/MRIReco.jl/runs/6123878388?check_suite_focus=true#step:6:373)
storage_type(::AbstractMatrix{T}) where T at /home/runner/.julia/packages/LinearOperators/ER4po/src/abstract.jl:169 …
```
=> Potential Bugfix

docs/make.jl
With this change, a new workflow named "documenter/deploy" appears in the list of checks when the docs have finished building.
Clicking on "details" takes you to the docs resulting from the pull request.
=> use push_preview = true in docs deploy

src/linalg.jl, src/special-operators.jl
I didn't check, but unbound type parameters often cause performance issues, so this isn't merely cosmetic.
FTR, there's a relevant function in Test in stdlib for checking this stuff:
https://docs.julialang.org/en/v1/stdlib/Test/#Test.detect_unbound_args
=> remove unbound type parameters

src/DiagonalHessianApproximation.jl, test/test_diag.jl
I changed s from (1, 1, 1) to (1, 0, 1) in the unit tests because it so happens that when s = (1, 1, 1), the two updates coincide.
=> add diagonal PSB quasi-Newton update

src/kron.jl, test/test_kron.jl
The Kronecker product code currently does not deal with multiplication by scalars correctly. This is illustrated below:
```julia
using LinearOperators, LinearAlgebra
A = kron(opEye(2),I(1))
Matrix(2A)
```
This results in:
```
2×2 Matrix{Float64}:
1.0  0.0
0.0  1.0
```
when it should be 2 times identity.
=> fix for Kronecker product scaling

src/DiagonalHessianApproximation.jl, test/test_diag.jl
Following https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/pull/94, I added `reset!` functions that restore the QN operators to the identity operator.
At the same time, I spotted a bug with `SpectralGradient` where the push was not updating `d` in the closure `prod = (res, v, α, β) -> mulSquareOpDiagonal!(res, d, v, α, β)` (because `d` was a Real).
I fixed it by changing `d` to `[σ]` so that modifying `d[1]` modifies `mulSquareOpDiagonal!(res, d, v, α, β)` accordingly.
This modifies the way we update a `SpectralGradient`: we have to do `op.d[1] = 2.0` instead of `op.d = 2.0`, but since we are supposed to update this operator with `push!`, this should not break code.
Does the adding of the `reset!` function requires a new minor release `2.6.0`, or can we stick to a patch …
=> Add reset function for Diagonal QN operators, fix bug SpectralGradient

Project.toml, ext/LinearOperatorsChainRulesCoreExt.jl, src/LinearOperators.jl, test/runtests.jl, test/test_chainrules.jl
This PR implements chainrules for the product of a linear operator with vectors and is a fix for issue #278 .
To avoid adding additional dependencies, the chainrules are implemented in the extension `LinearOperatorsChainRulesCoreExt`. Thus, they will only be loaded if the module `ChainRulesCore` is loaded. This cooresponds to the approach taken by `AbstractFFTs.jl`.
So far, this PR contains chainrules for the functions `*(op::AbstractLinearOperator{T}, v::AbstractVector{S})` and `*(v::Union{Transpose{S, V}, Adjoint{S, V}}, op::AbstractLinearOperator{T})`. There might exist further functions for which a chainrule might be useful, but to me these two appeared to contain most use-cases for the combination Zygote.jl / LinearOperators.jl
=> Implement chainrules

.github/workflows/Aqua.yml
The stale_deps check in Aqua fails since the use of Requires
=> Remove Aqua stale deps check

README.md, docs/src/index.md, src/abstract.jl, test/test_linop.jl
Hi everyone,
we have encountered in several of our packages a conflict between the functions `LinearOperators.shape` and `Distributions.shape` (https://github.com/JuliaImageRecon/LinearOperatorCollection.jl/issues/3#issuecomment-1822917316). Since the former is a duplicate of `size`, I was wondering if it would be feasible to drop `shape` from this package. To make everyone's life easier, I put those changes in a PR. 
This change would be breaking as we would drop an exported function. But fixes in other packages should be straight forward with a search & replace. 
Many thanks for considering!
=> [breaking] Remove shape function (duplicate of size)

src/adjtrans.jl, test/test_adjtrans.jl
=> Fix a bug in the derived adjoint

CITATION.bib, CITATION.cff, README.md
and also added @geoffroyleconte in the authors.
@software{Leconte_LinearOperators_jl_Linear_Operators_2023,
author = {Leconte, Geoffroy and Orban, Dominique and Soares Siqueira, Abel and contributors},
license = {MPL-2.0},
month = dec,
title = {{LinearOperators.jl: Linear Operators for Julia}},
url = {https://github.com/JuliaSmoothOptimizers/LinearOperators.jl},
version = {2.6.0},
year = {2023}
}
=> Use CITATION.cff

docs/src/index.md, docs/src/tutorial.md
I have noticed for a couple of weeks that the documentation build fails here.
I suspect the documentation to fail with 1.2.
Besides, there is the following warning:
```
┌ Warning: linkcheck 'https://juliasmoothoptimizers.github.io/tutorials/introduction-to-linear-operators/' status: 301, redirects to 'https://jso.dev/tutorials/introduction-to-linear-operators/'
└ @ Documenter C:\Users\tangi\.julia\packages\Documenter\Meee1\src\docchecks.jl:240
┌ Warning: linkcheck 'https://juliasmoothoptimizers.github.io' status: 301, redirects to 'https://jso.dev/'
└ @ Documenter C:\Users\tangi\.julia\packages\Documenter\Meee1\src\docchecks.jl:240
```
=> Fix documentation build

.github/workflows/Aqua.yml, Project.toml, test/Project.toml
There are issues with Aqua because there are no deps declared for ChainRulesCore:
```
LinearOperators [5c8ed15e-5a4c-59e4-a42b-c7e8811fb125] does not declare a compat entry for the following weakdeps:
1-element Vector{Base.PkgId}:
ChainRulesCore [d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4]
```
@tmigot
=> Fix Aqua issue

src/DiagonalHessianApproximation.jl, src/LinearOperators.jl, test/test_diag.jl
=> Separate diagonal quasi-Newton types

README.md
This pull request addresses issue #313 by correcting the Julia version compatibility information in the README. The current README states "Julia 1.3 and up". The corrected version now accurately reflects the correct compatibility as "Julia 1.6 and up."
Changes Made:
* Updated README.md to specify Julia version compatibility as "Julia 1.6 and up" on line 30.
Related Issue:
Closes #313
=> Review julia compatibility in readme #313

Project.toml, ext/LinearOperatorsCUDAExt.jl, src/LinearOperators.jl, src/constructors.jl
This PR adds a method for the `LinearOperator` function which has a correct default storage type for CUDA's `CuArray`.
This should (partially, it does not fix the upstream error in NLPModels.jl) fix #307, in particular this error is resolved:
```julia
julia> using CUDA, LinearOperators
julia> N = 8
8
julia> A = CUDA.rand(N, N);
julia> x = CUDA.rand(N);
julia> (A + opEye(Float32, N, S = typeof(x)));
ERROR: LinearOperatorException("storage types cannot be promoted to a concrete type")
Stacktrace:
[1] +(op1::LinearOperator{Float32, Int64, LinearOperators.var"#5#8"{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}, LinearOperators.var"#6#9"{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}, LinearOperators.var"#7#10"{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}, Vector{Float32}}, …
```
=> Add LinearOperator constructor for CUDA

src/lsr1.jl
@mohamedlaghdafhabiboullah Does this solve your allocation issue?
=> preallocate storage for LSR1 operator

ext/LinearOperatorsCUDAExt.jl
This PR implements `storage_type` for sparse `CuArrays. Since `CuArrays` and sparse `CuArrays` have no common CUDA-specific supertype, we have to handle it with a new case.
In the `storage_type` function I had to specify the memory type, unlike with the `CuArray`. This is because the LinearOperator constructor expects `S` to be a `DataType` and therefore doesn't accept `UnionAll`s
=> Add storage_type for Sparse CuArrays

src/DiagonalHessianApproximation.jl, test/test_diag.jl
@dpo With these changes, push! for diagonal QN operator should no longer allocate memory.
```julia
julia> using LinearOperators
julia> D = DiagonalAndrei(ones(2));
julia> s0 = sqrt(3) * ones(2)
julia> y0 = sqrt(2) *ones(2)
julia> @wrappedallocs push!(D, s0, y0)
0
julia> D = DiagonalPSB(ones(2))
julia> @wrappedallocs push!(D, s0, y0)
0
julia> D = SpectralGradient(1., 2);
julia> @wrappedallocs push!(D, s0, y0)
0
```
=> Eliminate useless allocation for diagonal quasi-Newton operators

src/DiagonalHessianApproximation.jl, test/test_diag.jl
@dpo This PR introduces a new DiagonalBFGS model for the Hessian, as described in Section 7.1 of this paper
https://www.researchgate.net/publication/384428920_A_Proximal_Modified_Quasi-Newton_Method_for_Nonsmooth_Regularized_Optimization
=> Dbfgs update

src/lsr1.jl
#367 
We should also add something in the tutorial [limited_memory_bfgs_and_sr1](https://jso.dev/tutorials/introduction-to-linear-operators/#limited_memory_bfgs_and_sr1) to say that since SR1 can be undefinite, only the forward operator is implemented.
=> Remove inverses in LSR1

src/abstract.jl, test/gpu/amdgpu.jl, test/gpu/nvidia.jl
I noticed that storage_types aren't correctly determined for lazily wrapped GPU arrays. In this PR I dispatch the storage_type based on the parent of the wrapper
=> Add correct storage_type for lazy wrapped GPU arrays (`adjoint`, `transpose`, `Diagonal`)

src/utilities.jl, test/test_normest.jl
See https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/issues/362
=> fix normest not working on rectangular matrices
